name: xeus-python-kernel
channels:
  - https://repo.mamba.pm/emscripten-forge
  - conda-forge
dependencies:
  - pip:
    # installing with conda fails because of extra dependencies
    - uproot
    - hist[plot]
    - pyodide-http
  - xeus-python
  - ipycanvas
  - numpy
  - awkward-cpp
  - awkward
  - boost-histogram
  - matplotlib
  - histoprint
  - mplhep
  - requests
